#!/usr/bin/env python3
"""Prepare MS2DeepScore resource manifest for CASMI hybrid benchmarks.

The pretrained model itself is large and is stored outside the repository under
`/home/zhome/ec_structure/external_ms_models/ms2deepscore`. This script writes a
small manifest that records expected files, hashes, and the next execution
requirements for a generator + MS2DeepScore hybrid benchmark.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
RESOURCE_DIR = Path("/home/zhome/ec_structure/external_ms_models/ms2deepscore")
OUTDIR = ROOT / "results" / "ms2deepscore_resource_manifest_v1"


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def file_row(name: str) -> dict[str, Any]:
    path = RESOURCE_DIR / name
    return {
        "file": name,
        "external_path": str(path),
        "exists": path.exists(),
        "size_bytes": path.stat().st_size if path.exists() else 0,
        "sha256": sha256(path) if path.exists() else "",
        "source": f"https://zenodo.org/api/records/17826815/files/{name}/content",
    }


def main() -> None:
    OUTDIR.mkdir(parents=True, exist_ok=True)
    files = [
        "settings.json",
        "embedding_model_settings.json",
        "embedding_evaluator.pt",
        "ms2deepscore_model.pt",
    ]
    rows = [file_row(name) for name in files]
    import pandas as pd

    pd.DataFrame(rows).to_csv(OUTDIR / "ms2deepscore_resource_manifest.csv", index=False)
    payload = {
        "stage": "ms2deepscore_resource_manifest_v1",
        "resource_dir": str(RESOURCE_DIR),
        "zenodo_record": "10.5281/zenodo.17826815",
        "title": "Dual mode MS2Deepscore model (MS2DeepScore >2.6)",
        "all_required_files_present": all(row["exists"] and row["size_bytes"] > 0 for row in rows),
        "model_file_in_git": False,
        "native_ms2deepscore_ready": False,
        "remaining_blockers": [
            "Install/import ms2deepscore and matchms in a stable Python environment.",
            "Build complete CASMI per-candidate predicted spectrum library.",
            "Score every query-candidate spectrum pair and label generated-candidate runs as hybrid baselines.",
        ],
    }
    (OUTDIR / "audit_summary.json").write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
    report = [
        "# MS2DeepScore Resource Manifest",
        "",
        "The official dual-mode pretrained MS2DeepScore resources were downloaded to external storage and are not committed to Git.",
        "",
        f"- External resource directory: `{RESOURCE_DIR}`",
        "- Zenodo record: `10.5281/zenodo.17826815`",
        "- Model committed to Git: `False`",
        "- Full CASMI MS2DeepScore ranking ready: `False`",
        "",
        "Remaining requirements are a stable `ms2deepscore`/`matchms` environment and a complete CASMI per-candidate spectrum library. If candidate spectra are generated by CFM-ID or ICEBERG, the result must be labeled as a generator + MS2DeepScore hybrid baseline.",
        "",
    ]
    (OUTDIR / "ms2deepscore_resource_manifest_report.md").write_text("\n".join(report), encoding="utf-8")


if __name__ == "__main__":
    main()
