#!/usr/bin/env python3
"""Run a CFM-ID + MS2DeepScore hybrid CASMI subset benchmark.

This is not native MS2DeepScore. Candidate spectra are generated by CFM-ID for
the already explicit candidate-limited CASMI subset, then MS2DeepScore ranks the
query spectrum against those generated candidate spectra.
"""

from __future__ import annotations

import argparse
import concurrent.futures as futures
import json
import os
import signal
import subprocess
import time
from collections import defaultdict
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from matchms import Spectrum
from ms2deepscore import MS2DeepScore
from ms2deepscore.models import load_model


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SUBSET_DIR = ROOT / "results" / "casmi2022_cfmid_native_subset_v1"
DEFAULT_OUTDIR = ROOT / "results" / "casmi2022_cfmid_ms2deepscore_hybrid_subset_v1"
DEFAULT_CFMID = Path("/home/zhome/ec_structure/external_ms_models/vendor/cfm-id-code/cfm/build_local_py36/bin/cfm-id")
DEFAULT_MODEL_ROOT = Path("/home/zhome/ec_structure/external_ms_models/vendor/cfm-id-code/cfm-pretrained-models/cfmid4")
DEFAULT_MS2DEEPSCORE_MODEL = Path("/home/zhome/ec_structure/external_ms_models/ms2deepscore/ms2deepscore_model.pt")


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")


def read_candidate_ids(path: Path) -> list[int]:
    ids: list[int] = []
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            text = line.strip()
            if not text:
                continue
            mol_id_text = text.split(maxsplit=1)[0]
            ids.append(int(mol_id_text))
    return ids


def ionmode_from_adduct(adduct: str) -> str:
    return "negative" if "-" in str(adduct) else "positive"


def parse_query_spectrum(path: Path, query_id: str, precursor_mz: float, ionmode: str) -> Spectrum:
    mzs: list[float] = []
    intensities: list[float] = []
    in_first_block = False
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            text = line.strip()
            if not text:
                continue
            if text.lower() in {"low", "med", "high"} or text.lower().startswith("energy"):
                if in_first_block:
                    break
                in_first_block = True
                continue
            if not in_first_block:
                continue
            parts = text.split()
            if len(parts) >= 2:
                mzs.append(float(parts[0]))
                intensities.append(float(parts[1]))
    return make_spectrum(
        mzs,
        intensities,
        {"id": f"query_{query_id}", "spectrum_id": query_id, "precursor_mz": float(precursor_mz), "ionmode": ionmode},
    )


def make_spectrum(mzs: list[float], intensities: list[float], metadata: dict[str, Any]) -> Spectrum:
    mz = np.asarray(mzs, dtype=np.float64)
    inten = np.asarray(intensities, dtype=np.float64)
    if len(mz) == 0:
        mz = np.asarray([0.0], dtype=np.float64)
        inten = np.asarray([0.0], dtype=np.float64)
    order = np.argsort(mz)
    mz = mz[order]
    inten = inten[order]
    max_int = float(np.max(inten)) if len(inten) else 0.0
    if max_int > 0:
        inten = inten / max_int
    return Spectrum(mz=mz, intensities=inten, metadata=metadata)


def parse_candidate_mgf(path: Path, precursor_mz: float, ionmode: str) -> dict[int, Spectrum]:
    grouped: dict[int, dict[float, float]] = defaultdict(dict)
    current_title = ""
    current_mz: list[float] = []
    current_int: list[float] = []

    def flush() -> None:
        nonlocal current_title, current_mz, current_int
        if not current_title or not current_mz:
            current_title = ""
            current_mz = []
            current_int = []
            return
        mol_id_text = current_title.split(";", 1)[0].strip()
        try:
            mol_id = int(mol_id_text)
        except ValueError:
            current_title = ""
            current_mz = []
            current_int = []
            return
        for mz, inten in zip(current_mz, current_int):
            key = round(float(mz), 4)
            grouped[mol_id][key] = max(grouped[mol_id].get(key, 0.0), float(inten))
        current_title = ""
        current_mz = []
        current_int = []

    with path.open(encoding="utf-8") as handle:
        for line in handle:
            text = line.strip()
            if not text:
                continue
            upper = text.upper()
            if upper == "BEGIN IONS":
                current_title = ""
                current_mz = []
                current_int = []
            elif upper == "END IONS":
                flush()
            elif text.startswith("TITLE="):
                current_title = text.split("=", 1)[1]
            elif text[0].isdigit():
                parts = text.split()
                if len(parts) >= 2:
                    current_mz.append(float(parts[0]))
                    current_int.append(float(parts[1]))
    spectra: dict[int, Spectrum] = {}
    for mol_id, peaks in grouped.items():
        mzs = list(peaks.keys())
        intensities = list(peaks.values())
        spectra[mol_id] = make_spectrum(
            mzs,
            intensities,
            {"id": f"candidate_{mol_id}", "candidate_mol_id": mol_id, "precursor_mz": float(precursor_mz), "ionmode": ionmode},
        )
    return spectra


def run_cfmid_mgf(task: dict[str, Any]) -> dict[str, Any]:
    query_id = str(task["query_id"])
    out_work = Path(task["out_work"])
    out_work.mkdir(parents=True, exist_ok=True)
    out_txt = out_work / f"cfmid_ranked_{query_id}.txt"
    out_mgf = out_work / f"cfmid_candidates_{query_id}.mgf"
    stdout_file = out_work / f"cfmid_mgf_{query_id}.stdout.log"
    stderr_file = out_work / f"cfmid_mgf_{query_id}.stderr.log"
    if task.get("resume") and out_mgf.exists() and out_mgf.stat().st_size > 0:
        return {"query_id": query_id, "status": "completed_cached", "elapsed_seconds": 0.0, "out_txt": str(out_txt), "out_mgf": str(out_mgf), "command": ""}
    model_dir = Path(task["model_root"]) / task["adduct"]
    cmd = [
        str(task["cfmid"]),
        str(task["spectrum_file"]),
        query_id,
        str(task["candidate_file"]),
        "-1",
        "10",
        "0.01",
        "0.001",
        str(model_dir / "param_output.log"),
        str(model_dir / "param_config.txt"),
        "DotProduct",
        "1",
        str(out_txt),
        str(out_mgf),
    ]
    started = time.time()
    with stdout_file.open("w", encoding="utf-8") as stdout, stderr_file.open("w", encoding="utf-8") as stderr:
        proc = subprocess.Popen(cmd, stdout=stdout, stderr=stderr, text=True, start_new_session=True)
        try:
            returncode = proc.wait(timeout=int(task["timeout_seconds"]))
            status = "completed" if returncode == 0 else "failed"
        except subprocess.TimeoutExpired:
            status = "timeout"
            try:
                os.killpg(proc.pid, signal.SIGTERM)
            except ProcessLookupError:
                pass
            try:
                proc.wait(timeout=10)
            except subprocess.TimeoutExpired:
                try:
                    os.killpg(proc.pid, signal.SIGKILL)
                except ProcessLookupError:
                    pass
    return {
        "query_id": query_id,
        "status": status,
        "elapsed_seconds": time.time() - started,
        "out_txt": str(out_txt),
        "out_mgf": str(out_mgf),
        "stdout_file": str(stdout_file),
        "stderr_file": str(stderr_file),
        "command": " ".join(cmd),
    }


def build_tasks(args: argparse.Namespace, query_df: pd.DataFrame, precursor_by_query: dict[str, float]) -> list[dict[str, Any]]:
    tasks = []
    for _, row in query_df.iterrows():
        query_id = str(row["query_id"])
        work = args.subset_dir / "work" / f"query_{query_id}"
        tasks.append(
            {
                "query_id": query_id,
                "true_candidate_id": str(row["true_candidate_id"]),
                "true_mol_id": int(str(row["true_candidate_id"]).replace("CASMI_MOL_", "")),
                "adduct": str(row["adduct"]),
                "ionmode": ionmode_from_adduct(str(row["adduct"])),
                "precursor_mz": float(precursor_by_query.get(query_id, np.nan)),
                "candidate_limit": int(row["candidate_limit"]),
                "candidate_pool_policy": str(row["candidate_pool_policy"]),
                "candidate_count": int(row["candidate_count"]),
                "spectrum_file": str(work / f"spectrum_{query_id}.txt"),
                "candidate_file": str(work / f"candidates_{query_id}.txt"),
                "out_work": str(args.outdir / "work" / f"query_{query_id}"),
                "cfmid": str(args.cfmid),
                "model_root": str(args.model_root),
                "timeout_seconds": args.timeout_seconds,
                "resume": args.resume,
            }
        )
    return tasks


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--subset-dir", type=Path, default=DEFAULT_SUBSET_DIR)
    parser.add_argument("--outdir", type=Path, default=DEFAULT_OUTDIR)
    parser.add_argument("--cfmid", type=Path, default=DEFAULT_CFMID)
    parser.add_argument("--model-root", type=Path, default=DEFAULT_MODEL_ROOT)
    parser.add_argument("--ms2deepscore-model", type=Path, default=DEFAULT_MS2DEEPSCORE_MODEL)
    parser.add_argument("--max-workers", type=int, default=2)
    parser.add_argument("--timeout-seconds", type=int, default=360)
    parser.add_argument("--resume", action="store_true")
    args = parser.parse_args()

    args.outdir.mkdir(parents=True, exist_ok=True)
    query_df = pd.read_csv(args.subset_dir / "casmi2022_cfmid_native_subset_query_results.csv")
    query_df = query_df[query_df["status"].eq("completed")].copy()
    subset_pred = pd.read_csv(args.subset_dir / "casmi2022_cfmid_native_subset_predictions.csv")
    precursor_by_query = subset_pred.drop_duplicates("query_id").set_index("query_id")["precursor_mz"].astype(float).to_dict()
    precursor_by_query.update({str(k): v for k, v in precursor_by_query.items()})
    tasks = build_tasks(args, query_df, precursor_by_query)

    cfmid_results: list[dict[str, Any]] = []
    with futures.ThreadPoolExecutor(max_workers=max(1, args.max_workers)) as executor:
        future_map = {executor.submit(run_cfmid_mgf, task): task for task in tasks}
        for future in futures.as_completed(future_map):
            result = future.result()
            cfmid_results.append(result)
            print(f"cfmid_mgf query={result['query_id']} status={result['status']} elapsed={result['elapsed_seconds']:.1f}s", flush=True)
    cfmid_results.sort(key=lambda r: int(r["query_id"]))

    model = load_model(args.ms2deepscore_model)
    similarity = MS2DeepScore(model, progress_bar=False)
    pred_rows: list[dict[str, Any]] = []
    query_rows: list[dict[str, Any]] = []
    commands = []
    results_by_query = {r["query_id"]: r for r in cfmid_results}
    task_by_query = {str(t["query_id"]): t for t in tasks}
    for query_id, task in task_by_query.items():
        result = results_by_query.get(query_id, {})
        commands.append({"query_id": query_id, "status": result.get("status", ""), "command": result.get("command", "")})
        if result.get("status") not in {"completed", "completed_cached"}:
            query_rows.append({"query_id": query_id, "status": result.get("status", "missing"), "true_rank": np.nan})
            continue
        query_spec = parse_query_spectrum(Path(task["spectrum_file"]), query_id, task["precursor_mz"], task["ionmode"])
        candidate_spectra = parse_candidate_mgf(Path(result["out_mgf"]), task["precursor_mz"], task["ionmode"])
        candidate_ids = [cid for cid in read_candidate_ids(Path(task["candidate_file"])) if cid in candidate_spectra]
        spectra = [candidate_spectra[cid] for cid in candidate_ids]
        scores = similarity.matrix(spectra, [query_spec])[:, 0] if spectra else np.asarray([])
        rows = []
        for cid, score in zip(candidate_ids, scores):
            rows.append({"candidate_mol_id": cid, "score": float(score), "is_correct": cid == task["true_mol_id"]})
        rows.sort(key=lambda x: (-x["score"], x["candidate_mol_id"]))
        true_rank = np.nan
        for rank, row in enumerate(rows, start=1):
            if row["is_correct"]:
                true_rank = float(rank)
            pred_rows.append(
                {
                    "dataset": "CASMI2022",
                    "model": "CFM-ID + MS2DeepScore hybrid subset",
                    "status": "completed",
                    "native_or_fallback": "cfmid_generated_spectra_ms2deepscore_similarity_hybrid",
                    "query_id": query_id,
                    "spectrum_id": query_id,
                    "true_candidate_id": task["true_candidate_id"],
                    "candidate_id": f"CASMI_MOL_{row['candidate_mol_id']}",
                    "candidate_mol_id": row["candidate_mol_id"],
                    "score": row["score"],
                    "rank": rank,
                    "is_correct": row["is_correct"],
                    "candidate_limit": task["candidate_limit"],
                    "candidate_pool_policy": task["candidate_pool_policy"],
                    "candidate_count": task["candidate_count"],
                }
            )
        finite = not pd.isna(true_rank)
        query_rows.append(
            {
                "dataset": "CASMI2022",
                "model": "CFM-ID + MS2DeepScore hybrid subset",
                "status": "completed",
                "native_or_fallback": "cfmid_generated_spectra_ms2deepscore_similarity_hybrid",
                "query_id": query_id,
                "spectrum_id": query_id,
                "true_candidate_id": task["true_candidate_id"],
                "candidate_limit": task["candidate_limit"],
                "candidate_pool_policy": task["candidate_pool_policy"],
                "candidate_count": task["candidate_count"],
                "candidate_spectra_count": len(candidate_ids),
                "true_rank": true_rank,
                "top1_correct": bool(finite and true_rank == 1),
                "top5_correct": bool(finite and true_rank <= 5),
                "top10_correct": bool(finite and true_rank <= 10),
                "reciprocal_rank": 0.0 if not finite else 1.0 / true_rank,
                "cfmid_mgf_status": result.get("status", ""),
                "cfmid_mgf_elapsed_seconds": result.get("elapsed_seconds", np.nan),
            }
        )

    pred_df = pd.DataFrame(pred_rows)
    qdf = pd.DataFrame(query_rows)
    completed = qdf[qdf["status"].eq("completed")].copy()
    rank_valid = completed[pd.to_numeric(completed["true_rank"], errors="coerce").notna()].copy()
    summary = {
        "dataset": "CASMI2022",
        "model": "CFM-ID + MS2DeepScore hybrid subset",
        "status": "completed_subset" if len(completed) == len(qdf) and len(qdf) else "partial_subset",
        "native_or_fallback": "cfmid_generated_spectra_ms2deepscore_similarity_hybrid",
        "n_queries_selected": int(len(qdf)),
        "n_queries_completed": int(len(completed)),
        "n_rank_valid_queries": int(len(rank_valid)),
        "candidate_limit": int(rank_valid["candidate_limit"].iloc[0]) if not rank_valid.empty else np.nan,
        "candidate_pool_policy": str(rank_valid["candidate_pool_policy"].iloc[0]) if not rank_valid.empty else "",
        "top1_accuracy": float(rank_valid["top1_correct"].mean()) if not rank_valid.empty else np.nan,
        "top5_accuracy": float(rank_valid["top5_correct"].mean()) if not rank_valid.empty else np.nan,
        "top10_accuracy": float(rank_valid["top10_correct"].mean()) if not rank_valid.empty else np.nan,
        "mean_reciprocal_rank": float(rank_valid["reciprocal_rank"].mean()) if not rank_valid.empty else np.nan,
        "median_true_rank": float(pd.to_numeric(rank_valid["true_rank"], errors="coerce").median()) if not rank_valid.empty else np.nan,
        "claim_guardrail": "Candidate spectra are generated by CFM-ID, so this is a CFM-ID + MS2DeepScore hybrid subset, not native MS2DeepScore and not a full CASMI benchmark.",
    }

    pred_df.to_csv(args.outdir / "casmi2022_cfmid_ms2deepscore_hybrid_subset_predictions.csv", index=False)
    qdf.to_csv(args.outdir / "casmi2022_cfmid_ms2deepscore_hybrid_subset_query_results.csv", index=False)
    pd.DataFrame([summary]).to_csv(args.outdir / "casmi2022_cfmid_ms2deepscore_hybrid_subset_summary.csv", index=False)
    pd.DataFrame(commands).to_csv(args.outdir / "cfmid_mgf_commands.csv", index=False)
    mirror = ROOT / "results" / "predictions" / "casmi2022_cfmid_ms2deepscore_hybrid_subset_predictions.csv"
    mirror.parent.mkdir(parents=True, exist_ok=True)
    pred_df.to_csv(mirror, index=False)
    audit = {
        "stage": "casmi2022_cfmid_ms2deepscore_hybrid_subset_v1",
        "status": summary["status"],
        "subset_source": str(args.subset_dir),
        "ms2deepscore_model": str(args.ms2deepscore_model),
        "cfmid": str(args.cfmid),
        "n_queries_selected": summary["n_queries_selected"],
        "n_queries_completed": summary["n_queries_completed"],
        "candidate_limit": summary["candidate_limit"],
        "candidate_pool_policy": summary["candidate_pool_policy"],
        "top1_accuracy": summary["top1_accuracy"],
        "top5_accuracy": summary["top5_accuracy"],
        "top10_accuracy": summary["top10_accuracy"],
        "mean_reciprocal_rank": summary["mean_reciprocal_rank"],
        "claim_guardrail": summary["claim_guardrail"],
    }
    write_json(args.outdir / "audit_summary.json", audit)
    report = [
        "# CASMI2022 CFM-ID + MS2DeepScore Hybrid Subset",
        "",
        summary["claim_guardrail"],
        "",
        "## Summary",
        "",
        "\n".join(f"- `{key}`: `{value}`" for key, value in summary.items()),
        "",
    ]
    (args.outdir / "casmi2022_cfmid_ms2deepscore_hybrid_subset_report.md").write_text("\n".join(report), encoding="utf-8")


if __name__ == "__main__":
    main()
