#!/usr/bin/env python3
"""Verify the external MS2DeepScore environment and pretrained model."""

from __future__ import annotations

import json
import subprocess
import time
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
ENV_PYTHON = Path("/home/zhome/ec_structure/external_ms_models/envs/ms2deepscore_casmi/bin/python")
MODEL_PATH = Path("/home/zhome/ec_structure/external_ms_models/ms2deepscore/ms2deepscore_model.pt")
OUTDIR = ROOT / "results" / "ms2deepscore_environment_verification_v1"


def run_probe() -> dict:
    code = (
        "import importlib.metadata as md, json, time, torch, ms2deepscore, matchms; "
        "from ms2deepscore.models import load_model; "
        f"p={str(MODEL_PATH)!r}; "
        "t=time.time(); model=load_model(p); elapsed=time.time()-t; "
        "print(json.dumps({"
        "'ms2deepscore_version': md.version('ms2deepscore'), "
        "'matchms_version': md.version('matchms'), "
        "'torch_version': torch.__version__, "
        "'torch_cuda_available': torch.cuda.is_available(), "
        "'model_path': p, "
        "'model_class': type(model).__name__, "
        "'model_load_seconds': elapsed"
        "}, sort_keys=True))"
    )
    completed = subprocess.run([str(ENV_PYTHON), "-c", code], capture_output=True, text=True, timeout=300, check=False)
    payload = {
        "command": " ".join([str(ENV_PYTHON), "-c", "<probe>"]),
        "returncode": completed.returncode,
        "stdout": completed.stdout.strip(),
        "stderr": completed.stderr.strip()[-4000:],
    }
    if completed.returncode == 0 and completed.stdout.strip():
        payload.update(json.loads(completed.stdout.strip().splitlines()[-1]))
        payload["status"] = "verified"
    else:
        payload["status"] = "failed"
    return payload


def main() -> None:
    OUTDIR.mkdir(parents=True, exist_ok=True)
    started = time.time()
    payload = run_probe()
    payload.update(
        {
            "stage": "ms2deepscore_environment_verification_v1",
            "env_python": str(ENV_PYTHON),
            "model_exists": MODEL_PATH.exists(),
            "model_size_bytes": MODEL_PATH.stat().st_size if MODEL_PATH.exists() else 0,
            "elapsed_seconds_total": time.time() - started,
            "candidate_spectrum_library_ready": False,
            "full_casmi_ms2deepscore_ranking_ready": False,
            "remaining_blocker": "complete CASMI per-candidate spectrum library and query-candidate scoring wrapper are still required",
        }
    )
    (OUTDIR / "audit_summary.json").write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
    pd.DataFrame([payload]).to_csv(OUTDIR / "ms2deepscore_environment_verification.csv", index=False)
    report = [
        "# MS2DeepScore Environment Verification",
        "",
        f"Status: `{payload.get('status')}`",
        "",
        f"Python: `{ENV_PYTHON}`",
        f"Model: `{MODEL_PATH}`",
        f"MS2DeepScore: `{payload.get('ms2deepscore_version', '')}`",
        f"MatchMS: `{payload.get('matchms_version', '')}`",
        f"Torch: `{payload.get('torch_version', '')}`; CUDA available: `{payload.get('torch_cuda_available', '')}`",
        f"Model load class: `{payload.get('model_class', '')}`; load seconds: `{payload.get('model_load_seconds', '')}`",
        "",
        "Full CASMI MS2DeepScore ranking is still not ready because a complete per-candidate spectrum library and scoring wrapper are required. If candidate spectra are generated by CFM-ID or ICEBERG, the benchmark must be labeled as a generator + MS2DeepScore hybrid baseline.",
        "",
    ]
    (OUTDIR / "ms2deepscore_environment_verification_report.md").write_text("\n".join(report), encoding="utf-8")


if __name__ == "__main__":
    main()
